# Generated by Django 2.2 on 2021-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('i_d', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
