# Generated by Django 2.2 on 2021-06-24 19:11

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfield',
            name='teacher_details',
            field=models.ForeignKey(default=student.models.get_default, on_delete=django.db.models.deletion.CASCADE, to='student.Teacher'),
        ),
    ]
